### ISSUE TITLE
Add Command History and Navigation

### ISSUE THREAD

**Issue by AmeyaKhanzode** [acmpesuecc/Shell#4]
Add support for command history using the arrow keys (up/down) so that users can navigate through previously executed commands.

**Comment by anirudh-os** [comment]
Can I have this issue assigned ?

**Comment by 2sumithrasuresh** [comment]
Can i be assigned this issue?

**Comment by Roshr2211** [comment]
Can you assign me the issue. I am ready with the workflow
- Raw Mode: The terminal is switched to raw mode to capture input byte-by-byte, including special keys like arrow keys. When the shell detects an escape sequence  it looks for the up (A) or down (B) arrow keys.

- History Management: The shell maintains a history buffer (history[]) to store commands. When the up/down arrow is pressed, the shell navigates through the history, displaying the command in the prompt.

- Buffer Resizing: If the command input exceeds the buffer, the buffer is reallocated dynamically to handle longer input.

**Comment by AmeyaKhanzode** [comment]
!assign @Roshr2211

**Comment by AmeyaKhanzode** [comment]
!assign @Roshr2211

**Comment by Aanirudhh** [comment]
assign me this issue

**Comment by AmeyaKhanzode** [comment]
!assign @Aanirudhh

**Comment by AmeyaKhanzode** [comment]
!deassign @Aanirudhh

**Comment by AmeyaKhanzode** [comment]
!assign @Roshr2211

**Comment by AmeyaKhanzode** [comment]
!assign @Roshr2211

**Comment by RohanChirbi** [comment]
Can I get assigned to this issue please?

**Comment by Roshr2211** [comment]
im done ameya

**Comment by AmeyaKhanzode** [comment]
!deassign @Roshr2211

**Comment by AmeyaKhanzode** [comment]
!assign @Roshr2211

**Comment by AmeyaKhanzode** [comment]
!deassign @Roshr2211

**Comment by RohanChirbi** [comment]
withdraw

**Comment by KaparthyReddy** [comment]
Kindly assign this.

**Comment by AmeyaKhanzode** [comment]
!assign @Roshr2211

**Comment by AmeyaKhanzode** [comment]
!assign @Roshr2211

**Comment by AmeyaKhanzode** [comment]
!deassign @Roshr2211

**Comment by KaparthyReddy** [comment]
could u assign this

**Comment by Anirudh10070** [comment]
please assign this to me

**Comment by anirudh-os** [comment]
@AmeyaKhanzode Heyy can u assign this to me ??

**Comment by anirudh-os** [comment]
@AmeyaKhanzode  Hello ?
