### ISSUE TITLE
Support for Signal Handling (Ctrl+C, Ctrl+Z)

### ISSUE THREAD

**Issue by AmeyaKhanzode** [acmpesuecc/Shell#5]
While the shell is running, implement a function to handle interrupts when ctrl+c or ctrl+z is pressed.

**Comment by anirudh-os** [comment]
Can I be assigned with this issue ?

**Comment by AmeyaKhanzode** [comment]
!assign @anirudh-os

**Comment by anirudh-os** [comment]
Uh I am not assigned yet

**Comment by AmeyaKhanzode** [comment]
are you assigned some other issue in a different repo?

**Comment by AmeyaKhanzode** [comment]
are you assigned some other issue in a different repo?

**Comment by 2sumithrasuresh** [comment]
can i be assigned this?

**Comment by AmeyaKhanzode** [comment]
!assign @2sumithrasuresh

**Comment by Am3li1** [comment]
can i be assigned?

**Comment by AmeyaKhanzode** [comment]
!assign @Am3li1

**Comment by 2sumithrasuresh** [comment]
It's not getting assigned?

**Comment by Harinihegde** [comment]
could you assign this?

**Comment by AmeyaKhanzode** [comment]
!assign @2sumithrasuresh

**Comment by AmeyaKhanzode** [comment]
@2sumithrasuresh do u need an extension in time?

**Comment by 2sumithrasuresh** [comment]
yes

**Comment by AmeyaKhanzode** [comment]
!assign @2sumithrasuresh

**Comment by AmeyaKhanzode** [comment]
!deassign @2sumithrasuresh

**Comment by AmeyaKhanzode** [comment]
!assign @2sumithrasuresh

**Comment by AmeyaKhanzode** [comment]
!deassign

**Comment by AmeyaKhanzode** [comment]
!assign @2sumithrasuresh

**Comment by pushkar-gr** [comment]
@AmeyaKhanzode can I have this issue ?

**Comment by AmeyaKhanzode** [comment]
!deassign

**Comment by AmeyaKhanzode** [comment]
!deassign @2sumithrasuresh
